homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - python2
  - python3
  - dockutil
  - jq
  - wget
  - gpg
  - packer
  - vault
  - terraform
  - terraform-docs
  - pinentry-mac
  - aws-okta
  - node
  - nomad
  - tflint
  - tmux
  - bash

homebrew_cask_apps:
  - alfred
  - iterm2
  - google-chrome
  - omnifocus
  - 1password
  - 1password-cli
  - bartender
  - toggl
  - logos
  - docker
  - firefox
  - aws-vault
  - vlc
  - calibre
  - duet
  - ubersicht
  - dash
  - java
  - handbrake
  - vagrant
  - intellij-idea
  - pycharm
  - datagrip
  - google-cloud-sdk
  - keybase
  - parallels
  - google-drive-file-stream
  - freedom
  - microsoft-office
  - omnioutliner
  - steam
  - notion
  - send-to-kindle
  - boxcryptor

mas_installed_apps:
  - { id: 803453959, name: "Slack" }
  - { id: 1176895641, name: "Spark" }
  - { id: 1091189122, name: "Bear"}
  - { id: 451907568, name: "Paprika Recipe Manager" }
  - { id: 407963104, name: "Pixelmator" }
  - { id: 905384638, name: "Filebot" }
  - { id: 441258766, name: "Magnet" }
  - { id: 405399194, name: "Kindle" }
  - { id: 1094748271, name: "Contacts+" }
  - { id: 572491815, name: "Textastic" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1055511498, name: "Day One" }
  - { id: 1369500258, name: "Anesidora" }
  - { id: 777233759, name: "Focus - Time Manager" }
  - { id: 528726140, name: "Mountain" }
  - { id: 1198319098, name: "MarsEdit" }
  - { id: 1295203466, name: "Remote Desktop 10" }
  - { id: 975937182, name: "Fantastical 2" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items:
  - serverless

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Safari
    path: /Applications/Safari.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Messages
    path: /System/Applications/Messages.app
    pos: 5
  - name: Music
    path: /System/Applications/Music.app
    pos: 6
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 7
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 8
