homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers/
  - versent/homebrew-taps
  - aws/tap

homebrew_installed_packages:
  - python3
  - node
  - dockutil
  - wget
  - gpg
  - tmux
  - jq
  - yq
  - awscli
  - tflint
  - packer
  - vault
  - tfenv
  - terraform
  - terraform-docs
  - pre-commit
  - gawk
  - go
  - gimme-aws-creds
  - aws-iam-authenticator
  - aws-sam-cli
  - ffmpeg
  - gcloud
  - ripgrep
  - cowsay


homebrew_cask_apps:
  - bartender
  - docker
  - vlc
  - calibre
  - google-chrome
  - vagrant
  - dash
  - zoomus
  - notion
  - slack
  - spotify
  - logitech-options
  - alacritty

mas_installed_apps:
  - { id: 405399194, name: "Kindle" }
  - { id: 1295203466, name: "Remote Desktop 10" }
  - { id: 497799835, name: "Xcode" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items: []
  

dockitems_to_remove:
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV
  - Safari
  - App Store

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Firefox
    path: /Applications/Firefox.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Messages
    path: /System/Applications/Messages.app
    pos: 5
  - name: Music
    path: /System/Applications/Music.app
    pos: 6
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 7
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 8
