homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - versent/homebrew-taps
  - aws/tap

homebrew_installed_packages:
  - python3
  - node
  - dockutil
  - wget
  - gpg
  - tmux
  - jq
  - yq
  - awscli
  - tflint
  - packer
  - vault
  - terraform
  - terraform-docs
  - pre-commit
  - gawk
  - go
  - ffmpeg
  - ripgrep
  - cowsay
  - nvim
  - rust
  - aws-cli
  - sls
  - kubectl
  - yarn
  - pulumi
  - bazel
  - docker
  - helm

homebrew_cask_apps:
  - bartender
  - docker
  - vlc
  - calibre
  - google-chrome
  - vagrant
  - dash
  - zoomus
  - notion
  - slack
  - spotify
  - logitech-options
  - alacritty
  - xquartz
  - vscodium
  - discord

mas_installed_apps: []
#   - { id: 405399194, name: "Kindle" }
#   - { id: 1295203466, name: "Remote Desktop 10" }
#   - { id: 497799835, name: "Xcode" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items: 
  - typescript  

dockitems_to_remove:
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV
  - Safari
  - App Store
  - Launchpad

dockitems_to_persist: {}
  # - name: System Preferences
  #   path: "/Applications/System Preferences.app"
  #   pos: 1
