---
- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: "{{ dockitems_to_remove }}"

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist }}"

- name: Hide the Dock
  shell: defaults write com.apple.dock autohide -bool true

- name: Resize the Dock
  shell: defaults write com.apple.dock tilesize -int 50
  
- name: Restart the Dock
  shell: killall Dock
