---
- name: Clone the dotfiles directory.
  git:
    repo: "{{ dotfiles_repo }}"
    version: "{{ dotfiles_branch }}"
    dest: "/Users/{{ homebrew_whoami.stdout }}/.config/dotfiles"
    update: yes
    accept_hostkey: yes
    depth: 1
    force: yes

- name: Ensure the dotfiles bootstrap.sh is executable
  file:
    path: "/Users/{{ homebrew_whoami.stdout }}/.config/dotfiles/bootstrap.sh"
    mode: '0755'

  
- name: Run the dotfiles bootstrap.sh
  command: "/Users/{{ homebrew_whoami.stdout }}/.config/dotfiles/bootstrap.sh"
