---
- include_tasks: oh-my-zsh.yml

- name: Get current account's username.
  shell: whoami
  register: homebrew_whoami
  changed_when: false
  check_mode: no

# Clone dotfiles
- name: Clone the dotfiles directory.
  git:
    repo: "{{ dotfiles_repo_https }}"
    version: "{{ dotfiles_branch }}"
    dest: "/Users/{{ homebrew_whoami.stdout }}/.config/dotfiles"
    update: yes
    force: yes
    accept_hostkey: yes
    depth: 1
# Ansible is struggling to clone over SSH, saying Permission denied (publickey) even though it's a public repo.
# I'm switching to use HTTPS and overwriting origin afterwards so I can get on with my day.

- name: set repo to use SSH instead of HTTPS
  shell: "cd /Users/{{ homebrew_whoami.stdout }}/.config/dotfiles && git remote set-url origin {{ dotfiles_repo_ssh }}"
    
- name: Ensure the dotfiles bootstrap.sh is executable
  file:
    path: "/Users/{{ homebrew_whoami.stdout }}/.config/dotfiles/bootstrap.sh"
    mode: '0755'

- name: Run the dotfiles bootstrap.sh
  command: "/Users/{{ homebrew_whoami.stdout }}/.config/dotfiles/bootstrap.sh -f"

- name: Install Pip Libraries
  pip:
    name: "{{ pip_items }}"
    executable: pip3
    extra_args: "--ignore-installed"

- name: Install Ruby Gems
  gem:
    name: "{{ item }}"
  with_items: "{{ gem_items }}"

- name: Install Node Packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_items }}"

- name: Remove all crap from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: "{{ dockitems_to_remove }}"

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist }}"

- name: Hide the Dock
  shell: defaults write com.apple.dock autohide -bool true

- name: Resize the Dock
  shell: defaults write com.apple.dock tilesize -int 50

- name: Update Homebrew
  shell: brew upgrade

- name: Update Homebrew Cask
  shell: brew cask upgrade

# - name: Set Wallpaper
#   shell: osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/Users/{{ homebrew_whoami.stdout }}/Documents/wallpaper/{{ wallpaper_file }}"'

- name: Restart the Dock
  shell: killall Dock

- name: use SSH for this repo instead of HTTPS
  shell: "cd /Users/{{ homebrew_whoami.stdout }}/.config/macos-config && git remote set-url origin git@github.com:cyclingwithelephants/macos-config.git"
 
